### PR TITLE
Add more arg checks

### PR DESCRIPTION
**Pull request by jafingerhut**
Inspired by some CLJ tickets requesting extra checks on arguments to some functions in clojure.core and clojure.java.io

### CODE REVIEW

**Comment by jafingerhut** [comment]
This is the last group of changes I have implemented as of today.

**Comment by jafingerhut** [comment]
Dude, your github photo is a different person now :-)

**Comment by frenchy64** [comment]
:) Do these only throw errors if the original function throws an error? I tried to keep that property previously, and otherwise only give a warning.

**Comment by jafingerhut** [comment]
Wow, that was significantly more tedious than I expected for partition and partition-all.

With the latest commit, the new wrappers should not only give errors when the original would either throw an exception, or go into an infinite loop.  Otherwise, it will only issue a warning.

More strangeness in testing when I tried to define a macro that checks if dynalint issues a warning.  I do not see why the macro I tried to write for this does not work.

**Comment by frenchy64** [comment]
Hehe nice work!

**Pull request merged**
