### PR TITLE
Remove most varargs

### PR DESCRIPTION
**Pull request by jafingerhut**
This also removes all dynalint checking for predicates like clojure.core/char?, since dynalint wasn't really doing any additional checking for those.

### CODE REVIEW

**Comment by frenchy64** [comment]
It still seems useful to have arity checks on the predicates no?

**Comment by jafingerhut** [comment]
The only predicates I've removed from dynalint with this change are 1-arg predicates that allow any type as an argument.  The difference in exceptions, first without, then with, dynalint # arg checking is shown below.  Does the dynalint version make that much difference in the information you get, or clarity?

;; without dynalint
user=> (string? "foo" "bar")
ArityException Wrong number of args (2) passed to: core/string?  clojure.lang.AFn.throwArity (AFn.java:429)
user=> (require '[dynalint.lint :as dl])
nil
user=> (dl/lint)
:ok
user=> (string? "foo" "bar")
ExceptionInfo ERROR (Dynalint id 1): Wrong number of arguments to clojure.core/string?: 2  dynalint.lint/error (lint.clj:105)

**Comment by jafingerhut** [comment]
Another related question: If you do believe that the dynalint arity warnings are preferable, shouldn't dynalint wrap *all* Clojure functions that do not accept every arity?  Why only the type predicate functions?

**Comment by frenchy64** [comment]
I think dynalint should wrap all core functions.

**Comment by jafingerhut** [comment]
Understood.  I will add back in the type predicate function wrappings that I removed, and let you know when the updated pull request is ready (in case Github doesn't auto-notify you of that event).

**Comment by jafingerhut** [comment]
I have added back in all of the 1-arg functions I removed, for which dynalint only checks their arity, and currently does no other checks, with one exception.  nil? I did not add back in, because it is inline, and the way it was attempted to be wrapped had no effect (or at least not the correct effect.)

**Comment by frenchy64** [comment]
The check for nil? works for higher-order usages.

**Comment by jafingerhut** [comment]
The check for nil? works for higher-order usages when I try it in the REPL, e.g. (doall (map nil? [1] [2])) gives dynalint error with this latest patch, but for some reason it gives a normal ArityException when I try the commented out unit test.

**Comment by frenchy64** [comment]
Mystery!

**Pull request merged**
