### PR TITLE
Correct too strict checks

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by frenchy64** [comment]
Seems a little dangerous to use `string?` and other similar functions, since they're also linted. Might be ok here.

**Comment by frenchy64** [comment]
To be clear, I mean using `string?` in the contract checking might induce infinite mutual recursion.

**Comment by jafingerhut** [comment]
So an issue and/or pull request to replace lots of checker code with things like (instance? String x) instead of (string? x) and (.equals nil x) instead of (nil? x) is something you would want?

**Comment by frenchy64** [comment]
I don't know. Your unit tests seems to suggest otherwise. We probably just
need to be extra careful in the checks of these downstream functions.

**Pull request merged**
